import type { Metadata } from "next"
import "./globals.css"
import AuthProvider from "./components/providers/auth-provider"

export const metadata: Metadata = {
  title: "Synth Movies",
  description: "Generated by create next app",
  icons: {
    icon: "assets/logo.svg",
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
